/*************************************************************************\
*                  Copyright (C) Michael Kerrisk, 2018.                   *
*                                                                         *
* This program is free software. You may use, modify, and redistribute it *
* under the terms of the GNU General Public License as published by the   *
* Free Software Foundation, either version 3 or (at your option) any      *
* later version. This program is distributed without any warranty.  See   *
* the file COPYING.gpl-v3 for details.                                    *
\*************************************************************************/

/* ouch_sigaction.c

   Catch the SIGINT signal, generated by typing control-C (^C).
*/
#include <signal.h>
#include "tlpi_hdr.h"

static void             /* Handler for SIGINT signal */
sigHandler(int sig)
{
    printf("Ouch!\n");          /* UNSAFE (see Section 21.1.2) */
}

int
main(int argc, char *argv[])
{
    struct sigaction sa;

    sa.sa_flags = 0;               /* No flags */
    sa.sa_handler = sigHandler;    /* Handler function */
    sigemptyset(&sa.sa_mask);      /* Don't block additional signals
                                      during invocation of handler */
    if (sigaction(SIGINT, &sa, NULL) == -1)   /* Establish handler */
        errExit("sigaction");

    for (;;)
        pause();        /* Wait for a signal */
}
